---
- name: Handle Docker apt key
  apt_key:
    url: https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    state: "{{ docker_state }}"

- name: Handle Docker Repository
  apt_repository:
    repo: deb https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ docker_apt_repo_release }} stable
    state: "{{ docker_state }}"

- name: Install Docker apt package
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg2
      - software-properties-common
      - docker-ce
    state: present
    update_cache: yes
  when: docker_state == "present"
  retries: 3
  register: docker_apt_installation
  until: docker_apt_installation is success

- name: Uninstall Docker apt package
  apt:
    name: docker-ce
    state: absent
    autoremove: yes
  when: docker_state == "absent"

- name: Remove docker service files, binaries and data
  file:
    name: "{{ item }}"
    state: absent
  with_items:
    - /var/lib/docker
    - /etc/docker
  when: docker_state == "absent"
