---
- name: Handle Docker apt key
  apt_key:
    url: https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    state: "{{ 'present' if install_docker else 'absent' }}"

- name: Handle Docker Repository
  apt_repository:
    repo: deb https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ docker_repo_distro_release }} stable
    state: "{{ 'present' if install_docker else 'absent' }}"

- name: Install Docker apt package
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg2
      - software-properties-common
      - docker-ce
    state: present
    update_cache: yes
  when: install_docker
  retries: 3
  register: docker_apt_installation
  until: docker_apt_installation is success

- name: Uninstall Docker apt package
  apt:
    name: docker-ce
    state: absent
    autoremove: yes
  when: not install_docker
  notify: Reload systemd
