---

- name: Check if k3s is installed
  stat:
    path: /usr/local/bin/k3s
  register: stat_k3s_result

- name: Install k3s
  shell:
    cmd: curl -sfL https://get.k3s.io | sh -
  when: k3s_state == 'present' and not stat_k3s_result.stat.exists

- name: Fetch kubeconfig
  fetch:
    src: /etc/rancher/k3s/k3s.yaml
    dest: "{{ kubeconfig }}"
    flat: yes
  changed_when: false
  when: k3s_state == 'present'

- name: Replace server name in kubeconfig
  lineinfile:
    path: "{{ kubeconfig }}"
    regexp: "^    server: .*$"
    line: "    server: https://{{ ansible_hostname }}:6443"
  changed_when: false
  become: false
  delegate_to: localhost
  when: k3s_state == 'present'

- name: Uninstall k3s
  shell:
    cmd: /usr/local/bin/k3s-uninstall.sh
  when: "k3s_state == 'absent' and stat_k3s_result.stat.exists"
